Improve portability, allowing this to work on MacOS.
Perform minor refactoring of platform-specific code.

diff --git a/bin/texemail b/bin/texemail
--- a/bin/texemail
+++ b/bin/texemail
@@ -9,13 +9,21 @@ set -o nounset -o pipefail -o errexit
 run_texlint=1
 run_latexdiff=1
 
-uname_r="$(uname -r)"
+uname_a="$(uname -a)"
 
-if [[ "${uname_r,,}" == *microsoft* ]]; then
-    wsl=1
-else
-    wsl=0
-fi
+clip_program='>&2 echo "Failed to copy the above text to the clipboard."'
+
+case "${uname_a,,}" in
+    *microsoft*|*windows*)
+        clip_program='clip.exe'
+        ;;
+    *darwin*)
+        clip_program="$(which pbcopy)"
+        ;;
+    *)
+        clip_program="$(which xsel) --clipboard"
+        ;;
+esac
 
 function git_iso_date ()
 {
@@ -85,8 +93,5 @@ for revision_old in "$@"; do
     output+=("$diffpdfname: latexdiff against ${revision_old} (${date_old})")
 done
 
-if ((wsl)); then
-    printf '%s\n' "${output[@]}" | tee /dev/tty | clip.exe
-else
-    printf '%s\n' "${output[@]}" | tee /dev/tty | xsel --clipboard
-fi
+
+printf '%s\n' "${output[@]}" | tee /dev/tty | $clip_program
